export const defaultTheme = {
  colors: {
    white: '#FFFFFF',
    yellowDark: '#C47F17',
    yellow: '#DBAC2C',
    yellowLight: '#F1E9C9',
    purpleDark: '#4B2995',
    purple: '#8047F8',
    purpleLight: '#EBE5F9',
    red: '#FF9494',
    background: '#FAFAFA',
    baseCard: '#F3F2F2',
    baseInput: '#EDEDED',
    baseButton: '#E6E5E5',
    baseHover: '#D7D5D5',
    baseLabel: '#8D8686',
    baseText: '#574F4D',
    baseSubtitle: '#403937',
    baseTitle: '#272221',
  },
  fonts: {
    primary: 'Roboto',
    secondary: 'Baloo 2'.toString(),
  },
}
